### ISSUE TITLE
Manual BG Check in mmol/l doesn't render properly

### ISSUE THREAD

**Issue by yodax** [loopandlearn/LoopFollow#147]
When running LoopFollow with mmol/l as the units the manual BG check doesn't render properly. I've managed to fix this on my local install, but this change isn't PR worthy since it would break for mg/dl.

The problem is that the sgv value retrieved from Nightscout is in mmol/l and is then further converted back to mmol/l causing the value to be rendered at the bottom.

I've fixed this here, but a proper fix should probably during the import: https://github.com/jonfawcett/LoopFollow/blob/7ec66ce56a0d9c6cf67d91d939c4bd91cd66d359/LoopFollow/Controllers/Graphs.swift#L819

``` let value = ChartDataEntry(x: Double(bgCheckData[i].date), y: Double(bgCheckData[i].sgv), data: formatPillText(line1: bgUnits.toDisplayUnits(String(bgCheckData[i].sgv)), time: bgCheckData[i].date))```

Changed to:

```let value = ChartDataEntry(x: Double(bgCheckData[i].date), y: Double(bgCheckData[i].sgv * 18), data: formatPillText(line1: String(bgCheckData[i].sgv), time: bgCheckData[i].date))```

**Comment by bjornoleh** [comment]
This issue is still present. I tried the proposed fix about a while back, but that’s not a proper solution, and only really convert integer values. Jon said it was due to the finger reading BG values being stored as strings, but I don’t know. 

There is also a similar issue for the rendering of temp targets when using mmol units in LF. Possibly worthy of an separate issue report, or perhaps not?

**Comment by bjorkert** [comment]
Hi! I'm glad to report that this issues is fixed in the latest release with this PR: https://github.com/loopandlearn/LoopFollow/pull/288

@bjornoleh A separate mmol temp target issue would be great with some examples, I have not experienced that myself (probably since we are on Loop?).
