### ISSUE TITLE
Calender entry inconsistent after upgrade to iOS17 and watchOS 10

### ISSUE THREAD

**Issue by flyingpie101** [loopandlearn/LoopFollow#220]
I am having issues with the Calendar entries staying on my apple watch series 5.

Upgraded both devices today.

The LF calendar entries are being written successfully to the correct Cal.

But the sync happens, and then disappears from watch.

**Comment by bjorkert** [comment]
I experience the same thing. Calendar entries and calendar widget is no longer working. Carplay works 100% and using siri watch face is a workaround.

![F9E7F3BE-1CD8-4290-9457-D53522A3365E](https://github.com/loopandlearn/LoopFollow/assets/12718238/be95f1be-fc49-4dd3-bc9d-341e60727441)

**Comment by flyingpie101** [comment]
Update: It seems almost like once the time entry is more than 2ish mins past the start of entry , it no longer shows on watchface.  But if you click the cal day on watch, you can see the entry is there.

**Comment by aug0211** [comment]
This is a WatchOS issue unfortunately.

I do have a PR up which uses 5m calendar entries as an experiment - but it seems unrelated to LF or any other tool like Sugarmate and instead is Watch OS 10 specific.

**Comment by bjorkert** [comment]
We're tidying up the LoopFollow repo and noticed this issue has been inactive for a while. We're closing it to keep things organized. If this is still a concern or you have further insights, please don't hesitate to reopen or create a new issue.

This issue should be fixed in watchOS. Carplay and the Siri watch face works fine as a understand it.
